name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    
    - name: Deploy to GitHub Pages repository
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        mkdir -p pokedex-deploy
        cd pokedex-deploy
        git init
        git remote add origin https://$GH_PAT@github.com/drohack/drohack.github.io.git
        git pull origin main
        rm -rf pokedex
        mkdir -p pokedex
        mv ../pokedex/* pokedex/
        git add pokedex
        commit_output=$(git commit -m "Deploy updated pokedex from GitHub Actions" 2>&1)
        if echo "$commit_output" | grep -q "nothing to commit, working tree clean"; then
          echo "Warning: Nothing to commit, working tree clean"
        else
          git push -f origin main
        fi
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
