name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    
    - name: Deploy to GitHub Pages repository
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        mv pokedex pokedex-deploy/pokedex
        cd pokedex-deploy
        git init
        git remote add origin https://$GH_PAT@github.com/drohack/drohack.github.io.git
        git add .
        git commit -m "Deploy from GitHub Actions"
        git branch -M main
        git push -f origin main
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
